In [1]:
#Import Library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Load Dataset
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
# dataset preprocessing
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
# drop column - which column not required we can drop it
dataset= dataset.drop("User ID",axis=1)
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [5]:
#checking 0 and 1 counts in purchased column - also this is imbalanced Data 
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [6]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [7]:
#input and coutput columns
independent= dataset [['Age', 'EstimatedSalary','Gender_Male']]
dependent = dataset ['Purchased']

In [8]:
#input column size
independent.shape

(400, 3)

In [9]:
dependent.shape

(400,)

In [10]:
# train and test set split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=1/3,random_state=0)

#Standard Scaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train= sc.fit_transform(x_train)
x_test= sc.transform(x_test)

In [12]:
# Model Creation
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import GridSearchCV

param_grid = {'penalty':['l1','l2','elasticnet',None],'solver':['lbfgs','liblinear','saga'],'multi_class':['auto','ovr','multinomial']}

grid = GridSearchCV(LogisticRegression(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#sklearn.metrics.f1_score

# fitting the model for grid search 
grid.fit(x_train, y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
85 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 64, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1291, in fit
    fold_coefs_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose, prefer=prefer)(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\joblib\parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\joblib\_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 521, in _logistic_regression_path
    alpha = (1.0 / C) * (1 - l1_ratio)
                         ~~^~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1216, in fit
    self.coef_, self.intercept_, self.n_iter_ = _fit_liblinear(
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\svm\_base.py", line 1223, in _fit_liblinear
    solver_type = _get_liblinear_solver_type(multi_class, penalty, loss, dual)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\svm\_base.py", line 1062, in _get_liblinear_solver_type
    raise ValueError(
ValueError: Unsupported set of arguments: The combination of penalty='None' and loss='logistic_regression' is not supported, Parameters: penalty=None, loss='logistic_regression', dual=False

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1207, in fit
    multi_class = _check_multi_class(self.multi_class, solver, len(self.classes_))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 90, in _check_multi_class
    raise ValueError("Solver %s does not support a multinomial backend." % solver)
ValueError: Solver liblinear does not support a multinomial backend.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan 0.82554202 0.82876593 0.82773722 0.82876593 0.82773722
        nan        nan        nan 0.82876593        nan 0.82876593
        nan 0.82554202 0.82876593 0.82773722 0.82876593 0.82773722
        nan        nan        nan 0.82876593        nan 0.82876593
        nan        nan 0.82876593 0.82876593        nan 0.82876593
        nan        nan        nan 0.82876593        nan 0.82876593]
  warnings.warn(

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'multi_class': ['auto', 'ovr', 'multinomial'],
                         'penalty': ['l1', 'l2', 'elasticnet', None],
                         'solver': ['lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

In [14]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(x_test)

In [15]:
print(grid.best_params_)
table=pd.DataFrame.from_dict(re)
table

{'multi_class': 'auto', 'penalty': 'l1', 'solver': 'saga'}

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_multi_class,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000277,0.000346,0.000000,0.000000,auto,l1,lbfgs,"{'multi_class': 'auto', 'penalty': 'l1', 'solv...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
1,0.002517,0.004187,0.000562,0.000895,auto,l1,liblinear,"{'multi_class': 'auto', 'penalty': 'l1', 'solv...",0.804764,0.811321,0.66593,0.92351,0.922185,0.825542,0.094918,18
2,0.001079,0.001579,0.002735,0.001434,auto,l1,saga,"{'multi_class': 'auto', 'penalty': 'l1', 'solv...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
3,0.001502,0.001268,0.000000,0.000000,auto,l2,lbfgs,"{'multi_class': 'auto', 'penalty': 'l2', 'solv...",0.799620,0.811321,0.68205,0.92351,0.922185,0.827737,0.089864,14
4,0.001677,0.002881,0.004680,0.003828,auto,l2,liblinear,"{'multi_class': 'auto', 'penalty': 'l2', 'solv...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
5,0.003203,0.003923,0.001601,0.003203,auto,l2,saga,"{'multi_class': 'auto', 'penalty': 'l2', 'solv...",0.799620,0.811321,0.68205,0.92351,0.922185,0.827737,0.089864,14
6,0.001601,0.003203,0.000000,0.000000,auto,elasticnet,lbfgs,"{'multi_class': 'auto', 'penalty': 'elasticnet...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
7,0.003200,0.003919,0.000000,0.000000,auto,elasticnet,liblinear,"{'multi_class': 'auto', 'penalty': 'elasticnet...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
8,0.000253,0.000506,0.000000,0.000000,auto,elasticnet,saga,"{'multi_class': 'auto', 'penalty': 'elasticnet...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
9,0.003854,0.004012,0.000000,0.000000,auto,None,lbfgs,"{'multi_class': 'auto', 'penalty': None, 'solv...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
10,0.002655,0.003612,0.000000,0.000000,auto,None,liblinear,"{'multi_class': 'auto', 'penalty': None, 'solv...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
11,0.003793,0.004740,0.003200,0.003919,auto,None,saga,"{'multi_class': 'auto', 'penalty': None, 'solv...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
12,0.000000,0.000000,0.000000,0.000000,ovr,l1,lbfgs,"{'multi_class': 'ovr', 'penalty': 'l1', 'solve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
13,0.001600,0.003201,0.003425,0.004210,ovr,l1,liblinear,"{'multi_class': 'ovr', 'penalty': 'l1', 'solve...",0.804764,0.811321,0.66593,0.92351,0.922185,0.825542,0.094918,18
14,0.000325,0.000651,0.001925,0.003850,ovr,l1,saga,"{'multi_class': 'ovr', 'penalty': 'l1', 'solve...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
15,0.003526,0.004349,0.003201,0.003921,ovr,l2,lbfgs,"{'multi_class': 'ovr', 'penalty': 'l2', 'solve...",0.799620,0.811321,0.68205,0.92351,0.922185,0.827737,0.089864,14
16,0.003201,0.003920,0.000325,0.000651,ovr,l2,liblinear,"{'multi_class': 'ovr', 'penalty': 'l2', 'solve...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
17,0.003202,0.003922,0.001600,0.003200,ovr,l2,saga,"{'multi_class': 'ovr', 'penalty': 'l2', 'solve...",0.799620,0.811321,0.68205,0.92351,0.922185,0.827737,0.089864,14
18,0.003201,0.003921,0.000000,0.000000,ovr,elasticnet,lbfgs,"{'multi_class': 'ovr', 'penalty': 'elasticnet'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
19,0.000000,0.000000,0.000000,0.000000,ovr,elasticnet,liblinear,"{'multi_class': 'ovr', 'penalty': 'elasticnet'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
20,0.000000,0.000000,0.000000,0.000000,ovr,elasticnet,saga,"{'multi_class': 'ovr', 'penalty': 'elasticnet'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
21,0.004812,0.003929,0.001600,0.003200,ovr,None,lbfgs,"{'multi_class': 'ovr', 'penalty': None, 'solve...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
22,0.001606,0.003212,0.000000,0.000000,ovr,None,liblinear,"{'multi_class': 'ovr', 'penalty': None, 'solve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
23,0.000000,0.000000,0.000000,0.000000,ovr,None,saga,"{'multi_class': 'ovr', 'penalty': None, 'solve...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
24,0.000000,0.000000,0.000000,0.000000,multinomial,l1,lbfgs,"{'multi_class': 'multinomial', 'penalty': 'l1'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
25,0.000000,0.000000,0.000000,0.000000,multinomial,l1,liblinear,"{'multi_class': 'multinomial', 'penalty': 'l1'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
26,0.003125,0.006249,0.000602,0.001204,multinomial,l1,saga,"{'multi_class': 'multinomial', 'penalty': 'l1'...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
27,0.004731,0.006272,0.000000,0.000000,multinomial,l2,lbfgs,"{'multi_class': 'multinomial', 'penalty': 'l2'...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
28,0.003126,0.006251,0.000000,0.000000,multinomial,l2,liblinear,"{'multi_class': 'multinomial', 'penalty': 'l2'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
29,0.003125,0.006249,0.000602,0.001204,multinomial,l2,saga,"{'multi_class': 'multinomial', 'penalty': 'l2'...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
30,0.000000,0.000000,0.000000,0.000000,multinomial,elasticnet,lbfgs,"{'multi_class': 'multinomial', 'penalty': 'ela...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
31,0.000000,0.000000,0.000000,0.000000,multinomial,elasticnet,liblinear,"{'multi_class': 'multinomial', 'penalty': 'ela...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
32,0.003126,0.006251,0.000000,0.000000,multinomial,elasticnet,saga,"{'multi_class': 'multinomial', 'penalty': 'ela...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
33,0.000000,0.000000,0.006251,0.007656,multinomial,None,lbfgs,"{'multi_class': 'multinomial', 'penalty': None...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1
34,0.003126,0.006251,0.000000,0.000000,multinomial,None,liblinear,"{'multi_class': 'multinomial', 'penalty': None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
35,0.003125,0.006249,0.000000,0.000000,multinomial,None,saga,"{'multi_class': 'multinomial', 'penalty': None...",0.804764,0.811321,0.68205,0.92351,0.922185,0.828766,0.089565,1

In [16]:
# here going to use confusion matrix instead of R2_Score
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test,grid_predictions)
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[79  6]
 [10 39]]

In [17]:
# Classification report to find recall, f1_score, precision, support
from sklearn.metrics import classification_report
clf_report =classification_report(y_test,grid_predictions)
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.89      0.93      0.91        85
           1       0.87      0.80      0.83        49

    accuracy                           0.88       134
   macro avg       0.88      0.86      0.87       134
weighted avg       0.88      0.88      0.88       134

In [18]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'multi_class': 'auto', 'penalty': 'l1', 'solver': 'saga'}: 0.8794289739855382

In [19]:
#age_input=float(input("Age:"))
#salary_input=float(input("BMI:"))
#sex_male_input=int(input("Sex Male 0 or 1:"))
#classifier.predict([[age_input,salary_input,sex_male_input]])