In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train= sc.fit_transform(x_train)
x_test= sc.transform(x_test)
#  (Xi-Xmean)/Xstd

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid= {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'max_features': ['sqrt','log2'],'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [15]:
re=grid.cv_results_   # it will show disctionary format
re

{'mean_fit_time': array([0.00450578, 0.00341916, 0.00207882, 0.00236149, 0.00377145,
        0.00245366, 0.00279531, 0.0025939 , 0.01228075, 0.01054411,
        0.01338458, 0.01084247, 0.00871568, 0.00334997, 0.00381837,
        0.0025938 ]),
 'std_fit_time': array([0.00257749, 0.00178163, 0.00117014, 0.00212856, 0.00168953,
        0.0001624 , 0.0003831 , 0.0010648 , 0.000842  , 0.0021623 ,
        0.00150474, 0.00185452, 0.00466771, 0.00167902, 0.00081765,
        0.00081399]),
 'mean_score_time': array([0.00217142, 0.00030546, 0.00030475, 0.00126481, 0.00194612,
        0.0012773 , 0.00233364, 0.00267301, 0.00090656, 0.00033503,
        0.00076303, 0.00217848, 0.00173011, 0.00171175, 0.00173197,
        0.00090127]),
 'std_score_time': array([0.00296211, 0.00061092, 0.00060949, 0.00252962, 0.00029608,
        0.00048801, 0.00086447, 0.00138629, 0.00092464, 0.00067005,
        0.0006433 , 0.00049147, 0.00034679, 0.00045121, 0.00066868,
        0.00080948]),
 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                    'squared_error', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'absolute_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'poisson', 'poisson', 'poisson', 'poisson'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['sqrt', 'sqrt', 'log2', 'log2', 'sqrt', 'sqrt', 'log2',
                    'log2', 'sqrt', 'sqrt', 'log2', 'log2', 'sqrt', 'sqrt',
                    'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'squared_error',
   'max_features': 'sqrt',
   'splitter': 'best'},
  {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'absolute_error',
   'max_features': 'sqrt',
   'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'absolute_error',
   'max_features': 'log2',
   'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'log2', 'splitter': 'random'}],
 'split0_test_score': array([0.73260669, 0.62414492, 0.6711097 , 0.61444361, 0.60265956,
        0.71251998, 0.64444154, 0.70558077, 0.71711609, 0.71618787,
        0.65360054, 0.77410534, 0.63398807, 0.61714086, 0.73099745,
        0.60004516]),
 'split1_test_score': array([0.61045048, 0.53003567, 0.60178242, 0.49681419, 0.61150248,
        0.61119439, 0.65921911, 0.41207785, 0.55257077, 0.5773598 ,
        0.65127248, 0.61590681, 0.5906352 , 0.69219503, 0.65566969,
        0.54163143]),
 'split2_test_score': array([0.69972167, 0.57397192, 0.6005767 , 0.66596464, 0.6751101 ,
        0.5520626 , 0.61924804, 0.59652089, 0.52759618, 0.23229748,
        0.61953552, 0.56332774, 0.61119537, 0.52185518, 0.73642706,
        0.60376758]),
 'split3_test_score': array([0.55892159, 0.59088452, 0.59401741, 0.65475059, 0.62836134,
        0.49240685, 0.50625036, 0.58744117, 0.6669891 , 0.5968667 ,
        0.61445343, 0.6255434 , 0.55425087, 0.61595587, 0.64227503,
        0.62133284]),
 'split4_test_score': array([0.63796313, 0.60008213, 0.61219533, 0.58984672, 0.54354167,
        0.6185308 , 0.66071887, 0.63244302, 0.68893943, 0.60380546,
        0.66605261, 0.69259867, 0.60650208, 0.6292706 , 0.66913058,
        0.58204465]),
 'mean_test_score': array([0.64793271, 0.58382383, 0.61593631, 0.60436395, 0.61223503,
        0.59734292, 0.61797558, 0.58681274, 0.63064231, 0.54530346,
        0.64098291, 0.65429639, 0.59931432, 0.61528351, 0.68689996,
        0.58976433]),
 'std_test_score': array([0.0620952 , 0.03140128, 0.02819499, 0.06035356, 0.04248373,
        0.07344172, 0.05781454, 0.09676249, 0.07604082, 0.16387988,
        0.02028484, 0.07265953, 0.0264618 , 0.05448628, 0.0391918 ,
        0.02710988]),
 'rank_test_score': array([ 3, 15,  7, 10,  9, 12,  6, 14,  5, 16,  4,  2, 11,  8,  1, 13])}

In [16]:
grid_predictions=grid.predict(x_test)   # y_pred=regressor.predict(x_test)

In [17]:
table=pd.DataFrame.from_dict(re)   # it will show table format - grid
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004506,0.002577,0.002171,0.002962,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.732607,0.610450,0.699722,0.558922,0.637963,0.647933,0.062095,3
1,0.003419,0.001782,0.000305,0.000611,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.624145,0.530036,0.573972,0.590885,0.600082,0.583824,0.031401,15
2,0.002079,0.001170,0.000305,0.000609,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.671110,0.601782,0.600577,0.594017,0.612195,0.615936,0.028195,7
3,0.002361,0.002129,0.001265,0.002530,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.614444,0.496814,0.665965,0.654751,0.589847,0.604364,0.060354,10
4,0.003771,0.001690,0.001946,0.000296,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.602660,0.611502,0.675110,0.628361,0.543542,0.612235,0.042484,9
5,0.002454,0.000162,0.001277,0.000488,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.712520,0.611194,0.552063,0.492407,0.618531,0.597343,0.073442,12
6,0.002795,0.000383,0.002334,0.000864,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.644442,0.659219,0.619248,0.506250,0.660719,0.617976,0.057815,6
7,0.002594,0.001065,0.002673,0.001386,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.705581,0.412078,0.596521,0.587441,0.632443,0.586813,0.096762,14
8,0.012281,0.000842,0.000907,0.000925,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.717116,0.552571,0.527596,0.666989,0.688939,0.630642,0.076041,5
9,0.010544,0.002162,0.000335,0.000670,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.716188,0.577360,0.232297,0.596867,0.603805,0.545303,0.163880,16
10,0.013385,0.001505,0.000763,0.000643,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.653601,0.651272,0.619536,0.614453,0.666053,0.640983,0.020285,4
11,0.010842,0.001855,0.002178,0.000491,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.774105,0.615907,0.563328,0.625543,0.692599,0.654296,0.072660,2
12,0.008716,0.004668,0.001730,0.000347,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.633988,0.590635,0.611195,0.554251,0.606502,0.599314,0.026462,11
13,0.003350,0.001679,0.001712,0.000451,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.617141,0.692195,0.521855,0.615956,0.629271,0.615284,0.054486,8
14,0.003818,0.000818,0.001732,0.000669,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.730997,0.655670,0.736427,0.642275,0.669131,0.686900,0.039192,1
15,0.002594,0.000814,0.000901,0.000809,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.600045,0.541631,0.603768,0.621333,0.582045,0.589764,0.027110,13

In [18]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,grid_predictions)
print(r_score)
print("The R_score value for best parameter {}:".format(grid.best_params_))

0.713778872973174
The R_score value for best parameter {'criterion': 'poisson', 'max_features': 'log2', 'splitter': 'best'}:

In [ ]:
#age_input=float(input("Age:"))
#bmi_input=float(input("BMI:"))
#children_input=float(input("Children:"))
#sex_male_input=int(input("Sex Male 0 or 1:"))
#smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

In [ ]:
#Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

#print("Future_Prediction={}".format(Future_Prediction))