In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
independent= sc.fit_transform(independent)
#  (Xi-Xmean)/Xstd

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid= {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'max_features': ['sqrt','log2'],'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [9]:
re=grid.cv_results_
re

{'mean_fit_time': array([0.00452323, 0.00121927, 0.00384398, 0.004424  , 0.00527568,
        0.00192156, 0.005126  , 0.00080886, 0.02186022, 0.01854563,
        0.02237668, 0.01738749, 0.00363145, 0.00224853, 0.00322118,
        0.00362825]),
 'std_fit_time': array([0.00477531, 0.00161011, 0.00322496, 0.00465044, 0.00373884,
        0.00157946, 0.00370612, 0.00099065, 0.0043139 , 0.004324  ,
        0.0039111 , 0.00208547, 0.00370205, 0.00170404, 0.00275668,
        0.00374912]),
 'mean_score_time': array([0.00160618, 0.00020003, 0.00080085, 0.00160995, 0.00170846,
        0.00149026, 0.00040455, 0.00160694, 0.00210843, 0.00160494,
        0.00232258, 0.00268316, 0.00040488, 0.00161486, 0.00040336,
        0.00040336]),
 'std_score_time': array([0.00321236, 0.00040007, 0.00098084, 0.00321989, 0.00317353,
        0.00215622, 0.0008091 , 0.00321388, 0.00305138, 0.00320988,
        0.00317506, 0.0016814 , 0.00080976, 0.00136761, 0.00080671,
        0.00080671]),
 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                    'squared_error', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'absolute_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'poisson', 'poisson', 'poisson', 'poisson'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['sqrt', 'sqrt', 'log2', 'log2', 'sqrt', 'sqrt', 'log2',
                    'log2', 'sqrt', 'sqrt', 'log2', 'log2', 'sqrt', 'sqrt',
                    'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'squared_error',
   'max_features': 'sqrt',
   'splitter': 'best'},
  {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'absolute_error',
   'max_features': 'sqrt',
   'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'absolute_error',
   'max_features': 'log2',
   'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'log2', 'splitter': 'random'}],
 'split0_test_score': array([0.71967947, 0.68253524, 0.73885757, 0.71792979, 0.72571808,
        0.66306725, 0.75989176, 0.69444368, 0.7606295 , 0.70344831,
        0.67117729, 0.6887449 , 0.7294725 , 0.62653365, 0.66196396,
        0.71938357]),
 'split1_test_score': array([0.55600203, 0.59393517, 0.60999742, 0.48113231, 0.65592576,
        0.43707208, 0.68273195, 0.59188247, 0.54872798, 0.58726981,
        0.59396349, 0.60866792, 0.56556616, 0.61810704, 0.61348529,
        0.58892331]),
 'split2_test_score': array([0.73395197, 0.74375013, 0.72889504, 0.74035338, 0.70805569,
        0.71750644, 0.75740284, 0.63656681, 0.66348274, 0.6483137 ,
        0.64757925, 0.78910138, 0.72584211, 0.67348225, 0.74427295,
        0.62208269]),
 'split3_test_score': array([0.70545842, 0.71255997, 0.72449786, 0.70642267, 0.65371537,
        0.70793078, 0.65595578, 0.70938661, 0.70914659, 0.62965503,
        0.72461117, 0.72302694, 0.67495225, 0.67258189, 0.71717409,
        0.62345256]),
 'split4_test_score': array([0.75273723, 0.67965505, 0.73632939, 0.61541225, 0.66180255,
        0.62244693, 0.63090416, 0.60661061, 0.56755532, 0.66392654,
        0.60517078, 0.73627098, 0.62499725, 0.56859573, 0.73606164,
        0.71164369]),
 'mean_test_score': array([0.69356582, 0.68248711, 0.70771546, 0.65225008, 0.68104349,
        0.6296047 , 0.6973773 , 0.64777804, 0.64990843, 0.64652268,
        0.6485004 , 0.70916242, 0.66416606, 0.63186011, 0.69459159,
        0.65309717]),
 'std_test_score': array([0.07053999, 0.050014  , 0.04912764, 0.09554999, 0.02991126,
        0.10207985, 0.05264984, 0.04672914, 0.08120603, 0.03831984,
        0.04724335, 0.05972161, 0.06235598, 0.03901427, 0.04968051,
        0.0524987 ]),
 'rank_test_score': array([ 5,  6,  2, 10,  7, 16,  3, 13, 11, 14, 12,  1,  8, 15,  4,  9])}

In [10]:
grid_predictions=grid.predict(independent)

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004523,0.004775,0.001606,0.003212,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.719679,0.556002,0.733952,0.705458,0.752737,0.693566,0.070540,5
1,0.001219,0.001610,0.000200,0.000400,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.682535,0.593935,0.743750,0.712560,0.679655,0.682487,0.050014,6
2,0.003844,0.003225,0.000801,0.000981,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.738858,0.609997,0.728895,0.724498,0.736329,0.707715,0.049128,2
3,0.004424,0.004650,0.001610,0.003220,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.717930,0.481132,0.740353,0.706423,0.615412,0.652250,0.095550,10
4,0.005276,0.003739,0.001708,0.003174,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.725718,0.655926,0.708056,0.653715,0.661803,0.681043,0.029911,7
5,0.001922,0.001579,0.001490,0.002156,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.663067,0.437072,0.717506,0.707931,0.622447,0.629605,0.102080,16
6,0.005126,0.003706,0.000405,0.000809,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.759892,0.682732,0.757403,0.655956,0.630904,0.697377,0.052650,3
7,0.000809,0.000991,0.001607,0.003214,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.694444,0.591882,0.636567,0.709387,0.606611,0.647778,0.046729,13
8,0.021860,0.004314,0.002108,0.003051,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.760630,0.548728,0.663483,0.709147,0.567555,0.649908,0.081206,11
9,0.018546,0.004324,0.001605,0.003210,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.703448,0.587270,0.648314,0.629655,0.663927,0.646523,0.038320,14
10,0.022377,0.003911,0.002323,0.003175,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.671177,0.593963,0.647579,0.724611,0.605171,0.648500,0.047243,12
11,0.017387,0.002085,0.002683,0.001681,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.688745,0.608668,0.789101,0.723027,0.736271,0.709162,0.059722,1
12,0.003631,0.003702,0.000405,0.000810,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.729472,0.565566,0.725842,0.674952,0.624997,0.664166,0.062356,8
13,0.002249,0.001704,0.001615,0.001368,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.626534,0.618107,0.673482,0.672582,0.568596,0.631860,0.039014,15
14,0.003221,0.002757,0.000403,0.000807,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.661964,0.613485,0.744273,0.717174,0.736062,0.694592,0.049681,4
15,0.003628,0.003749,0.000403,0.000807,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.719384,0.588923,0.622083,0.623453,0.711644,0.653097,0.052499,9

In [12]:
from sklearn.metrics import r2_score
r_score = r2_score(dependent,grid_predictions)
print(r_score)
print("The R_score value for best parameter {}:".format(grid.best_params_))

0.9824332685253571
The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'splitter': 'random'}:

In [13]:
#age_input=float(input("Age:"))
#bmi_input=float(input("BMI:"))
#children_input=float(input("Children:"))
#sex_male_input=int(input("Sex Male 0 or 1:"))
#smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

In [14]:
#Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

#print("Future_Prediction={}".format(Future_Prediction))

In [15]:
import pickle
filename="finalized_model_DT.sav"

In [16]:
pickle.dump(grid,open(filename,'wb'))

In [21]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))
preinput = sc.transform([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
preinput

Age: 12
BMI: 345
Children: 0
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

C:\Users\santhiya\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-1.93717259, 51.56518465, -0.90861367,  0.98959079,  1.97058663]])

In [23]:
loaded_model=pickle.load(open("finalized_model_DT.sav",'rb'))
Future_Prediction=grid.predict(preinput)
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[44501.3982]